/**
 * TspSoapService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.oristartech.tsp.ws.soap;

public interface TspSoapService extends java.rmi.Remote {
    public java.lang.String memberTransactionCancel(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pOldTransactionNo, java.lang.String pTransactionNo, java.lang.String pChannelType, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String giveTicket(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pArrayIn, java.lang.String pLoginNum, java.lang.String pChannel, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String modifyActivityExeTime(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pRuleIds, java.lang.String pAmounts, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String memberConsumeOrder(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pLoginNum, java.lang.String pOrderCode, java.lang.String pOrderFormNum, java.lang.String pTransactionTime, java.lang.Float pAmount, java.lang.String pGoodsCategory, java.lang.Float pTicketAmount, java.lang.Float pGoodsAmount, java.lang.String pTicketNum, java.lang.String pSessionNumAndDiscountNum, java.lang.Float pTicketIntegralAmount, java.lang.Float pGoodsIntegralAmount, java.lang.Float pIntegralMultiple, java.lang.String pRuleIdsAndRunTimes, java.lang.String pOrderPay, java.lang.String pOrderGoods, java.lang.String pRuleGoodsAmounts, java.lang.String pChannel, java.lang.String pOperator, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryOrderStatus(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pOrderCode, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryMerchandise(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pPageSize, java.lang.String pPageNum, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String getIntegralOrderInfoByOrderNum(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pOrderFormNum, java.lang.String pTerminalFlowNum, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String submitOrder(java.lang.String submitOrderXml) throws java.rmi.RemoteException;
    public java.lang.String queryFilmInfo(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pPlanDate, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String releaseSeat(java.lang.String releaseSeatXml) throws java.rmi.RemoteException;
    public java.lang.String queryIntegralFlowInfo(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pLoginNum, java.lang.String pStartDate, java.lang.String pEndDate, java.lang.String pPageSize, java.lang.String pPageNum, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String createMerOrder(java.lang.String createMerOrderXml) throws java.rmi.RemoteException;
    public java.lang.String applyFetchTicket(java.lang.String applyFetchTicketXml) throws java.rmi.RemoteException;
    public java.lang.String autoMatchMarketActivityExeV3P0(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pFacts, java.lang.String pIsOnePriceResult, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryCinemaInfo(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryDiscountActivity(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pFacts, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryScreenSeat(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pScreenCode, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryMemberInfo(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pLoginNum, java.lang.String pLmsPassword, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String resetMemberPassword(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pLoginNum, java.lang.String pResetPassword, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryPlanInfo(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pPlanDate, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String modifyMemberPassword(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pLoginNum, java.lang.String pOldPassword, java.lang.String pNewPassword, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String verficationOfOne(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pTicketNum, java.lang.String pPasswd, java.lang.String pDataPacket, java.lang.String pLoginNum, java.lang.String pChannel, java.lang.String pTerminalNum, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryOrderDetail(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pOrderCode, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryTicketOrder(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pTicketNum, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryRetailTicketInfo(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryTicketOfMarketing(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String fetchTicket(java.lang.String fetchTicketXml) throws java.rmi.RemoteException;
    public java.lang.String memberRefund(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pFlowNum, java.lang.String pTransactionNo, java.lang.Float pAmount, java.lang.Float pTicketAmount, java.lang.Float pGoodsAmount, java.lang.String pChannelType, java.lang.String pGoods, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String memberConsumeV2P0(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pLoginNum, java.lang.String pLmsPassword, java.lang.String pOrderCode, java.lang.String pTransactionNo, java.lang.Float pAmount, java.lang.String pGoodsCategory, java.lang.Float pTicketAmount, java.lang.Float pGoodsAmount, java.lang.String pTicketNum, java.lang.String pChannelType, java.lang.String pOperator, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String modifyMemberInfo(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pLoginNum, java.lang.String pPassword, java.lang.String pMobileNum, java.lang.String pUserName, java.lang.String pSex, java.lang.String pBirthday, java.lang.String pCreditNum, java.lang.String pEmail, java.lang.String pOperator, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryMemberFlowInfo(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pLoginNum, java.lang.String pStartDate, java.lang.String pEndDate, java.lang.String pPageSize, java.lang.String pPageNum, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String getMoneyOrderByOrderNum(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pOrderFormNum, java.lang.String pTerminalFlowNum, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String memberConsume(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pLoginNum, java.lang.String pLmsPassword, java.lang.String pChannelType, java.lang.Float pAmount, java.lang.String pOrderCode, java.lang.String pTransactionNo, java.lang.Float pTicketAmount, java.lang.Float pGoodsAmount, java.lang.Float pIntegralAmount, java.lang.Float pIntegralMultiple, java.lang.String pGoods, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryAvailCinema(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pLoginNum, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryFavorableActivity(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pFacts, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryOrders(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pTransactionType, java.lang.String pOrderSource, java.lang.String pIsShowDetail, java.lang.String pTransactionDate, java.lang.String pPageSize, java.lang.String pPageNum, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String preordainRetailTicketRevocation(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pArrayIn, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String integralTransactionCancel(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pOldTransactionNo, java.lang.String pTransactionNo, java.lang.String pChannelType, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryCinemaParams(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String getFilmInfo(java.lang.String pAppCode, java.lang.String pPublishDateStart, java.lang.String pPublishDateEnd, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String memberCharge(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pLoginNum, java.lang.String pChargeType, java.lang.String pChargeTypeName, java.lang.String pChannelType, java.lang.String pAccountType, java.lang.Float pChargeAmount, java.lang.String pChargeActivityId, java.lang.String pChargeClass, java.lang.String pOrderCode, java.lang.String pTransactionNo, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String lockSeat(java.lang.String lockSeatXml) throws java.rmi.RemoteException;
    public java.lang.String queryTicketInfo(java.lang.String queryTicketInfoXml) throws java.rmi.RemoteException;
    public java.lang.String modifyMemberLoginPassword(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pLoginNum, java.lang.String pOldLoginPassword, java.lang.String pNewLoginPassword, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryPlanInfoAndSeatLevelPrice(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pPlanStartDate, java.lang.String pPlanEndDate, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryDeliveryStatus(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pPrintNo, java.lang.String pVerifyCode, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String ticketConsume(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pTicketNum, java.lang.String pPasswd, java.lang.String pRuleId, java.lang.String pChannel, java.lang.String pTerminalFlowNum, java.lang.String pTicketSaleOrderNo, java.lang.Float pCreditPrice, java.lang.Float pAmount, java.lang.String pTerminalNum, java.lang.String pConsumeTime, java.lang.String pTicketOrderGoods, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryPlanInfoByDatePeriod(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pPlanStartDate, java.lang.String pPlanEndDate, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String ticketCheckUnlock(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pTicketNum, java.lang.String pChannel, java.lang.String pTerminalNum, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String phoneNumRegAndCharge(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pMobileNum, java.lang.String pLmsPassword, java.lang.String pLoginPasswd, java.lang.String pLevelCode, java.lang.String pRegCinemaMember, java.lang.String pName, java.lang.String pSex, java.lang.String pBirthday, java.lang.String pCreditNum, java.lang.String pEmail, java.lang.String pOrderCode, java.lang.String pTransactionNo, java.lang.Float pChargeAmount, java.lang.String pChargeType, java.lang.String pChargeTypeName, java.lang.String pAccountType, java.lang.String pChannelType, java.lang.String pCheckAmountLimit, java.lang.String pOperator, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryPlanSeat(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pFeatureAppNo, java.lang.String pStatus, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String cancelOrder(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pPrintNo, java.lang.String pVerifyCode, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String integralRefund(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pConsumeType, java.lang.String pFlowNum, java.lang.String pTransactionNo, java.lang.Float pAmount, java.lang.String pChannelType, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String preordainRetailTicket(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pArrayIn, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String verifyMemberLogin(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pLoginNum, java.lang.String pLmsPassword, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String memberRefundV2P0(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pFlowNum, java.lang.String pTransactionNo, java.lang.Float pAmount, java.lang.String pGoodsCategory, java.lang.Float pTicketAmount, java.lang.Float pGoodsAmount, java.lang.String pTicketNum, java.lang.String pChannelType, java.lang.String pOperator, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryMemberTickets(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pLoginNum, java.lang.String pLmsPassword, java.lang.String pTicketStatus, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String giveIntegral(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pLoginNum, java.lang.String pChannelType, java.lang.Float pAmount, java.lang.String pOrderCode, java.lang.String pTransactionNo, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String submitMerOrder(java.lang.String submitMerOrderXml) throws java.rmi.RemoteException;
    public java.lang.String queryPlanSeatPrice(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pFeatureAppNo, java.lang.String pStatus, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryCinemaList(java.lang.String pAppCode, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String querySeatInfo(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pScreenCode, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String verficationOfMany(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pTicketNum, java.lang.String pPasswd, java.lang.String pTicketSaleOrderNo, java.lang.String pLoginNum, java.lang.String pChannel, java.lang.String pTerminalNum, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryTransactionInfo(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pTradeTimeStart, java.lang.String pTradeTimeEnd, java.lang.String pTradeType, java.lang.String pTradeChannel, java.lang.String pGdTradeCode, java.lang.String pIsReturnDetail, java.lang.String pPageSize, java.lang.String pPageNo, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String modifyActivityExeTimeV2P0(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pRuleIds, java.lang.String pAmounts, java.lang.String pOrderFormNum, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryTicketRuleInfo(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pTicketNum, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String activityInvokeMember(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pLoginNum, java.lang.String pRuleId, java.lang.String pActionId, java.lang.String pOldTransactionNo, java.lang.String pChannelType, java.lang.String pTransactionNo, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String memberRefundOrder(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pOrderCode, java.lang.String pOrderFormNum, java.lang.String pOldOrderCode, java.lang.String pTransactionTime, java.lang.Float pAmount, java.lang.String pGoodsCategory, java.lang.Float pTicketAmount, java.lang.Float pGoodsAmount, java.lang.String pTicketNum, java.lang.String pSessionNumAndDiscountNum, java.lang.Float pTicketIntegralAmount, java.lang.Float pGoodsIntegralAmount, java.lang.String pCancelMarketingActivity, java.lang.String pOrderPay, java.lang.String pOrderGoods, java.lang.String pRuleGoodsAmounts, java.lang.String pChannel, java.lang.String pOperator, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String integralConsume(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pLoginNum, java.lang.String pLmsPassword, java.lang.String pChannelType, java.lang.String pConsumeType, java.lang.Float pAmount, java.lang.String pOrderCode, java.lang.String pTransactionNo, java.lang.String pGoods, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String checkMemberByLoginPwd(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pLoginNum, java.lang.String pLoginPasswd, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryChargeActivity(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pLoginNum, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String getCinemaAllPlan(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryMemberLevel(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryFilmInfoByDatePeriod(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pPlanStartDate, java.lang.String pPlanEndDate, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String getPlanSeatState(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pFeatureAppNo, java.lang.String pStatus, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryFavorablePrice(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pFacts, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String phoneNumReg(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pMobileNum, java.lang.String pLmsPassword, java.lang.String pLoginPasswd, java.lang.String pName, java.lang.String pSex, java.lang.String pBirthday, java.lang.String pCreditNum, java.lang.String pEmail, java.lang.String pOperator, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryCinemaBusinessStatus(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pBusinessType, java.lang.String pBusinessDate, java.lang.String pBusinessStatus, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String queryTicketValidityPeriod(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pTicketNums, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String ticketReturnProcess(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pTicketNum, java.lang.String pChannel, java.lang.String pTerminalNum, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String extractRetailTicket(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pArrayIn, java.lang.String pMobileNum, java.lang.String pIsSendMsg, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
    public java.lang.String generalInvoker(java.lang.String pAppCode, java.lang.String pCinemaCode, java.lang.String pActionName, java.lang.String pUUID, java.lang.String pActionParam, java.lang.String pCompress, java.lang.String pVerifyInfo) throws java.rmi.RemoteException;
}
